name: CacomixtlePad
description: An Android Control Pad for 3D Printers
version: 1.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  usb_serial: ^0.5.0
  file_picker: ^10.1.9
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  provider: ^6.1.5
  shared_preferences: ^2.0.15
  wakelock_plus: ^1.2.8
  network_info_plus: ^5.0.0
  

  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lang/

flutter_native_splash:
  color: "#fff2d8"
  image: assets/icons/Csplash.png
  android_gravity: fill
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/icons/Csplash.png
    android_gravity: fill
    icon_background_color: "#fff2d8"
    color: "#fff2d8"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/splash5_padded.png"  
